#!/bin/zsh
# shellcheck disable=SC1071,SC2296

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Function to check if a command exists before adding to Oh My Zsh
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Initialize an empty plugins array
plugins=()

# Add plugins conditionally
command_exists docker && plugins+=(docker)
command_exists docker-compose && plugins+=(docker-compose)
command_exists mosh && plugins+=(mosh)
command_exists sudo && plugins+=(sudo)
command_exists code && plugins+=(vscode)

# Source Oh My Zsh
[ -f "$ZSH/oh-my-zsh.sh" ] && source "$ZSH/oh-my-zsh.sh"

# znap configuration and plugins
[[ -f $ZSH_CUSTOM/plugins/zsh-snap/znap.zsh ]] ||
  git clone https://github.com/marlonrichert/zsh-snap.git "$ZSH_CUSTOM/plugins/zsh-snap"
source ~/.oh-my-zsh/custom/plugins/zsh-snap/znap.zsh
zstyle ':znap:*:*' git-maintenance off

[[ -f $ZSH_CUSTOM/themes/powerlevel10k/powerlevel10k.zsh-theme ]] ||
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$ZSH_CUSTOM/themes/powerlevel10k"

# enable completion
autoload -Uz compinit
compinit -d ~/.cache/zcompdump
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# FZF history search
zle     -N            fzf-history-widget

# Key bindings
bindkey -M emacs '^S' fzf-history-widget
bindkey -M vicmd '^S' fzf-history-widget
bindkey -M viins '^S' fzf-history-widget

if [[ ! $ITERM_PROFILE ]]; then
  # skip/delete forward/backward a word
  bindkey $'^[[1;3D' vi-backward-blank-word
  bindkey $'^[[1;3C' vi-forward-blank-word
  bindkey $'^[[1;^H' backward-kill-word
  bindkey $'^[[1;^?' kill-word
  bindkey $'^[[1~' beginning-of-line
  bindkey $'^[[4~' end-of-line
  bindkey $'^[[1;9D' beginning-of-line
  bindkey $'^[[1;9C' end-of-line
fi

# znap plugins
znap source Aloxaf/fzf-tab
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source unixorn/fzf-zsh-plugin

# Visual Studio Code shell integration
vscode_shell_integration() {
  . "$(code --locate-shell-integration-path zsh)"
  unfunction vscode_shell_integration
}
[[ "$TERM_PROGRAM" == "vscode" ]] && zle -N vscode_shell_integration

# Other shell integrations
iterm2_shell_integration() {
  source "$HOME/.iterm2_shell_integration.zsh"
  unfunction iterm2_shell_integration
}
[ -f "$HOME/.iterm2_shell_integration.zsh" ] && zle -N iterm2_shell_integration

fzf_integration() {
  source ~/.fzf.zsh
  unfunction fzf_integration
}
[ -f ~/.fzf.zsh ] && zle -N fzf_integration

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Ensure PATH is unique
typeset -U PATH

# Import aliases
[ -f "$HOME/.aliases" ] && source "$HOME/.aliases"
