#!/bin/bash
# shellcheck disable=SC1090,SC1091

# Fix compaudit
compfix() {
    if [ "$1" ]; then
        for i in "$@"; do chmod g-w "$i"; done
    else
        echo "Needs at least one argument"
    fi
}

# rsync shortcuts
alias rsync-copy='rsync -avz --progress -h'
alias rsync-move='rsync -avz --progress -h --remove-source-files'
alias rsync-update='rsync -avzu --progress -h'
alias rsync-synchronize='rsync -avzu --delete --progress -h'

# Shortcut to open tmux session 0
[ "$(command -v fzf)" ] || alias tm='tmux new -As0'

if ! command -v eza &>/dev/null; then             # ls aliases (if eza is not installed)
    alias ls='ls --color=auto' # add color to ls
    alias ll='ls -l'           # list files as a long list
    alias l='ls -lFh'          # list files as a long list, show size, type, human-readable
    alias la='ls -lAFh'        # list almost all files as a long list show size, type, human-readable
    alias lr='ls -tRFh'        # list files recursively sorted by date, show type, human-readable
    alias lt='ls -ltFh'        # list files as a long list sorted by date, show type, human-readable
    alias ldot='ls -ld .*'     # list dot files as a long list
    alias lS='ls -1FSsh'       # list files showing only size and name sorted by size
    alias lart='ls -1Fcart'    # list all files sorted in reverse of create/modification time (oldest first)
    alias lrt='ls -1Fcrt'      # list files sorted in reverse of create/modification time(oldest first)
    alias lsr='ls -lARFh'      # list all files and directories recursively
    alias lsn='ls -1'          # list files and directories in a single column
else                                              # if eza is installed, use that instead of ls
    alias ls='eza -bg'                            # list files with grid view and block size
    alias ll='eza -laFb'                          # list all files in long format, classify file type, show block size
    alias l='eza -1'                              # list files in single column format
    alias li='eza -1 --icons'                     # list files in single column format with icons for file type
    alias la='eza -1a'                            # list all files in single column format
    alias lt='eza -T --level=2'                   # display tree view with 2 levels deep
    alias l2='eza -T --level=2'                   # display tree view with 2 levels deep
    alias lt2='eza -T --level=2'                  # display tree view with 2 levels deep
    alias l3='eza -T --level=3'                   # display tree view with 3 levels deep
    alias lt3='eza -T --level=3'                  # display tree view with 3 levels deep
    alias lat='eza -aT --level=2'                 # display all files in tree view with 2 levels deep
    alias la2='eza -aT --level=2'                 # display all files in tree view with 2 levels deep
    alias lat2='eza -aT --level=2'                # display all files in tree view with 2 levels deep
    alias la3='eza -aT --level=3'                 # display all files in tree view with 3 levels deep
    alias lat3='eza -aT --level=3'                # display all files in tree view with 3 levels deep
    alias lf='eza -1 --group-directories-first'   # list files in single column format, directories displayed first
    alias lfa='eza -1a --group-directories-first' # list all files in single column format, directories displayed first
fi

# if bat is installed, use that instead of cat
if command -v bat &>/dev/null; then
    alias cat='bat -p'
fi

# head / tail / grep / miscellaneous shortcuts
alias h='history'                                               # show the command history
alias hs='history 0 | grep'                                     # search the command history
alias hsi='history 0 | grep -i'                                 # search the command history (case-insensitive)
alias grep='grep --color'                                       # grep with color output for matches
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} ' # recursive grep in files with line numbers, file names, 5 lines of context
alias t='tail -f'                                               # follow the end of a file in real time
alias H='| head'                                                # pipe to head command (show first few lines of input)
alias T='| tail'                                                # pipe to tail command (show last few lines of input)
alias G='| grep'                                                # pipe to grep command (search input)
alias L="| less"                                                # pipe to less command (paged output)
alias M="| most"                                                # pipe to most command (paged output)
alias LL="2>&1 | less"                                          # redirect standard error and standard output to less command
alias CA="2>&1 | cat -A"                                        # redirect standard error and standard output to cat -A command (show all special characters)
alias NE="2> /dev/null"                                         # redirect standard error to null (discard error output)
alias NUL="> /dev/null 2>&1"                                    # redirect both standard output and standard error to null (discard all output)
alias P="2>&1| pygmentize -l pytb"                              # redirect standard error and standard output to pygmentize command (syntax highlighting for python traceback)

# searching and sizing
alias dud='du -d 1 -h'                          # display the size of files at depth 1 in current location in human-readable form
alias duds='du -d 1 -h | sort -hr'              # same as above but sorted by size
[ "$(command -v duf)" ] || alias duf='du -sh *' # display the size of files in current location in human-readable form
alias ffil='find . -type f -name'               # find a file with the given name
alias fdir='find . -type d -name'               # find a file with the given name

# Use fzf to clear from zsh history
alias histfzf='history -w; cat .zsh_history | fzf > /tmp/rm; grep -vxFf /tmp/rm .zsh_history > .new_zsh_history; mv .new_zsh_history .zsh_history; rm /tmp/rm; history -r'

# SSH shortcuts
alias ska='eval "$(ssh-agent -s)"'       # start SSH agent
alias skm='ssh-add --apple-use-keychain' # add to agent (Mac)
alias skl='ssh-add'                      # add to agent (Linux)
alias sshk='kitty +kitten ssh'           # connect with kitty

# Remove line from ~/.ssh/known_hosts
rmknown() {
    if [ "$1" ]; then
        re='^[0-9]+$'
        if ! [[ $1 =~ $re ]]; then
            echo "Error: Not a number" >&2
        else
            gsed -i "$1"d ~/.ssh/known_hosts
            echo "Removed line $1"
        fi
    else
        echo "Error: No line number specified" >&2
    fi
}

# mosh
function mosh() {
    case "$1" in
    "calufrax" | "defiant")
        shift
        mosh --server=/opt/homebrew/bin/mosh-server "$@"
        ;;
    *)
        command mosh "$@"
        ;;
    esac
}
